baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
