baseURL = 'https://quack3rs.github.io/'
languageCode = 'en-us'
title = 'ctf writeups, maybe'
theme = 'nightfall'

[params]
sitedescription = 'hello'
published = false
readingTime = false

[menu]
	[[menu.header]]
		name = 'ctf writeups'
		weight = 0
		url = '/ctf'
